### ISSUE TITLE
Action failed

### ISSUE THREAD

**Issue by JasonSqz** [jtr13/edav2#5] opened 2022-01-28 04:47 UTC
I have added the content of histogram and learning R(Chapter1). However action kept failing throwing error of missing True/False. I tried commenting out each  section to locate the problem, which does not seem to work :(.

I am thinking of missing True/False in r chunks, but unable to find any.

**Comment by jtr13** [comment] 2022-01-28 22:40
Thanks, I'll look into it. It may be a problem beyond our control. For now it's best to work on a branch or not push to GitHub until we sort it out.

**Comment by jtr13** [comment] 2022-01-28 23:28
It's fixed now... for reasons that aren't entirely clear to me, taking out the emo package from DESCRIPTION and adding it back fixed it. The DESCRIPTION file was not previously formatted correctly so I think that messed things up. I'll explain more next time we meet what the GitHub Action steps are so you have a better sense of what it's doing. For now, note that if it's getting stuck in the setup-r-dependencies section then the problem is not in the .Rmd files. If your code is working for you locally, you can just tag me as soon as GitHub Actions fails. Otherwise it can be a frustrating process!

**Comment by JasonSqz** [comment] 2022-01-29 02:18
Great! I will raise an issue next time when Github action is not working. Can you also go through the contents we put up by now and see if there is change needed. (More content to be added tonight)

**Closed** 2022-01-29 04:40 UTC
